### ISSUE TITLE
Keychain issues due to NTP error while trying to install

### ISSUE THREAD

**Issue by genie137** [SpaceAceMonkey/spaceace-arch-kubernetes-unraid#12]
Hey, great guide ;)

I did have an issue in both VMs. 
I could not install packages trough Pacman because of issues with the keychain.

After some research this was due to the timesync.d service not working.
I followed the steps by elaiolado here: https://bbs.archlinux.org/viewtopic.php?id=283075

Essentially the following: 
1. Editing /etc/systemd/timesyncd.conf
2. Uncommenting the NTP and FallbackNTP lines.
3. Adding time.google.com at the NTP line (or copying the values from the FallbackNTP line to the NTP line as elaiolado did)
4. Saving
5. Restarting the systemd-timesyncd.service

**Comment by SpaceAceMonkey** [comment]
Interesting. Did you do anything differently from what is in the guide, such as using a different installation image, or installing in an environment other than Unraid? I have never experienced the issue you describe. I would like to narrow down the cause so I can address it in the guide if appropriate.

Thanks for the report.
