### ISSUE TITLE
"cni-bin-dir" is deprecated

### ISSUE THREAD

**Issue by Grennith** [SpaceAceMonkey/spaceace-arch-kubernetes-unraid#4]
Hi,
following the guide with the latest Arch (2023.08.01 as of writing) will install kubelet 1.27.4.

https://kubernetes.io/docs/concepts/extend-kubernetes/compute-storage-net/network-plugins/

> Prior to Kubernetes 1.24, the CNI plugins could also be managed by the kubelet using the cni-bin-dir and network-plugin command-line parameters. These command-line parameters were removed in Kubernetes 1.24, with management of the CNI no longer in scope for kubelet.

I suspect that the following kubeadm init fails to properly connect to the service as a consequence.
Omitting the "upload-certs" parameter have the kubeadm init pass.

**Comment by SpaceAceMonkey** [comment]
Thank you for the report. I'm hoping to have time to re-work the entire guide sometime this year to update several things, and I will add this to the list. Thanks, again.
