### ISSUE TITLE
Error that System has not been booted with systemd when setting timezone

### ISSUE THREAD

**Issue by Chaotic** [SpaceAceMonkey/spaceace-arch-kubernetes-unraid#5]
Following the guide and at the part to set the timezone and getting this error.  using the 2024-05-01 disk image of archlinux

![image](https://github.com/SpaceAceMonkey/spaceace-arch-kubernetes-unraid/assets/160479/36c189ca-8d1f-4052-bc5f-2c53b34c7be3)

**Comment by SpaceAceMonkey** [comment]
Hi. Thanks for the report. I believe the error you are experiencing is a result of being in the `arch-chroot` environment. I think step 3.3 on [this page](https://wiki.archlinux.org/title/Installation_guide#Time_zone) will fix the issue for you. The gist of it is to simply create the localtime symlink manually.

Please report back with whether or not this fixes the problem for you.

**Comment by Chaotic** [comment]
I actually just skipped that step and did it after the first reboot and it worked there.  I'll try it with that fix later when I set up another node.

**Comment by SpaceAceMonkey** [comment]
Thank you for the update. It sounds like the problem was the `chroot`, then. I will leave this issue open as a reminder to myself for when I update the guide, but either your solution or mine should work for anyone who has this issue in the meantime.
